title: Exoplanet and Planet Formation Workshop
description: Exoplanet and Planet Formation Workshop
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-include-cache

markdown: kramdown
theme: null
