title: EPF
description: Exoplanet and Planet Formation Workshop
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

markdown: kramdown
theme: null

header_pages:
  - philosophy.md
  - history.md
