title: EPF
description: Exoplanet and Planet Formation Workshop
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache

markdown: kramdown
theme: null

header_pages:
  - philosophy.md
  - history.md
